<?php
require_once '../includes/config.php';
require_once '../includes/functions.php';

requireLogin();
requireAdmin();

$success = '';
$error = '';
$shipment = null;

// Get shipment ID
if (!isset($_GET['shipment_id'])) {
    header('Location: manage_shipments.php');
    exit;
}

$shipmentId = intval($_GET['shipment_id']);

// Get shipment details
$stmt = $conn->prepare("SELECT s.*, u.full_name as customer_name, u.email as customer_email, u.phone as customer_phone
                       FROM shipments s
                       JOIN users u ON s.user_id = u.id
                       WHERE s.id = ?");
$stmt->bind_param('i', $shipmentId);
$stmt->execute();
$shipment = $stmt->get_result()->fetch_assoc();

if (!$shipment) {
    header('Location: manage_shipments.php');
    exit;
}

// Check if invoice already exists
$stmt = $conn->prepare("SELECT * FROM payments WHERE shipment_id = ?");
$stmt->bind_param('i', $shipmentId);
$stmt->execute();
$existingInvoice = $stmt->get_result()->fetch_assoc();

if ($existingInvoice) {
    $error = "Invoice already exists for this shipment. <a href='../view_invoice.php?id={$existingInvoice['id']}'>View Invoice</a>";
}

// Handle form submission
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['generate_invoice']) && !$existingInvoice) {
    $serviceFee = floatval($_POST['service_fee'] ?? 0);
    $customsDuty = floatval($_POST['customs_duty'] ?? 0);
    $portCharges = floatval($_POST['port_charges'] ?? 0);
    $otherFees = floatval($_POST['other_fees'] ?? 0);
    $currency = sanitize($_POST['currency'] ?? 'NAD');
    $notes = sanitize($_POST['notes'] ?? '');

    $totalAmount = $serviceFee + $customsDuty + $portCharges + $otherFees;

    if ($totalAmount <= 0) {
        $error = "Total amount must be greater than zero";
    } else {
        // Generate invoice number
        $invoiceNumber = generateInvoiceNumber($conn);

        // Prepare invoice details as JSON for notes
        $invoiceDetails = json_encode([
            'service_fee' => $serviceFee,
            'customs_duty' => $customsDuty,
            'port_charges' => $portCharges,
            'other_fees' => $otherFees,
            'notes' => $notes
        ]);

        // Insert into payments table
        $stmt = $conn->prepare("INSERT INTO payments (shipment_id, invoice_number, amount, currency, status, payment_method)
                               VALUES (?, ?, ?, ?, 'Pending', ?)");
        $paymentMethod = $invoiceDetails; // Store breakdown in payment_method field temporarily
        $stmt->bind_param('isdss', $shipmentId, $invoiceNumber, $totalAmount, $currency, $paymentMethod);

        if ($stmt->execute()) {
            $success = "Invoice generated successfully! Invoice Number: $invoiceNumber";

            // Optionally update shipment status to "Documents Submitted" if not already
            if ($shipment['status'] === 'Documents Pending') {
                updateShipmentStatus($conn, $shipmentId, 'Documents Submitted', 'Invoice generated by admin', $_SESSION['user_id']);
            }

            // Redirect to view invoice
            header("Location: ../view_invoice.php?id=" . $conn->insert_id);
            exit;
        } else {
            $error = "Failed to generate invoice. Please try again.";
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Generate Invoice - Admin</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="../assets/css/styles.css">
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="index.php">Trade Ocean Namibia - Admin</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="index.php">Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="manage_shipments.php">Shipments</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="manage_users.php">Users</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="../logout.php">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Dashboard Header -->
    <div class="dashboard-header">
        <div class="container">
            <h2>Generate Invoice</h2>
            <p class="mb-0 text-muted">Create invoice for shipment <?= htmlspecialchars($shipment['tracking_number']) ?></p>
        </div>
    </div>

    <div class="container mb-5">
        <!-- Success/Error Messages -->
        <?php if ($success): ?>
            <div class="alert alert-success alert-dismissible fade show">
                <?= $success ?>
                <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            </div>
        <?php endif; ?>

        <?php if ($error): ?>
            <div class="alert alert-danger alert-dismissible fade show">
                <?= $error ?>
                <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            </div>
        <?php endif; ?>

        <!-- Shipment Information -->
        <div class="card mb-4">
            <div class="card-header bg-info text-white">
                <h5 class="mb-0">Shipment Details</h5>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <p><strong>Tracking Number:</strong> <?= htmlspecialchars($shipment['tracking_number']) ?></p>
                        <p><strong>Customer:</strong> <?= htmlspecialchars($shipment['customer_name']) ?></p>
                        <p><strong>Email:</strong> <?= htmlspecialchars($shipment['customer_email']) ?></p>
                        <p><strong>Phone:</strong> <?= htmlspecialchars($shipment['customer_phone'] ?? 'N/A') ?></p>
                    </div>
                    <div class="col-md-6">
                        <p><strong>Origin:</strong> <?= htmlspecialchars($shipment['origin_port'] ?? 'N/A') ?></p>
                        <p><strong>Destination:</strong> <?= htmlspecialchars($shipment['destination_port']) ?></p>
                        <p><strong>Shipment Type:</strong> <?= htmlspecialchars($shipment['shipment_type']) ?></p>
                        <p><strong>Weight:</strong> <?= htmlspecialchars($shipment['total_weight']) ?> kg</p>
                        <p><strong>Status:</strong> <span class="<?= getStatusBadgeClass($shipment['status']) ?>"><?= htmlspecialchars($shipment['status']) ?></span></p>
                    </div>
                </div>
            </div>
        </div>

        <?php if (!$existingInvoice): ?>
        <!-- Invoice Generation Form -->
        <div class="card">
            <div class="card-header bg-primary text-white">
                <h5 class="mb-0">Invoice Details</h5>
            </div>
            <div class="card-body">
                <form method="POST" action="" id="invoiceForm">
                    <div class="row mb-3">
                        <div class="col-md-6">
                            <label for="service_fee" class="form-label">Service Fee</label>
                            <div class="input-group">
                                <input type="number" step="0.01" class="form-control" id="service_fee"
                                       name="service_fee" value="0.00" min="0" required>
                                <span class="input-group-text">NAD</span>
                            </div>
                            <small class="text-muted">Trade Ocean shipping and handling charges</small>
                        </div>
                        <div class="col-md-6">
                            <label for="customs_duty" class="form-label">Customs Duty</label>
                            <div class="input-group">
                                <input type="number" step="0.01" class="form-control" id="customs_duty"
                                       name="customs_duty" value="0.00" min="0">
                                <span class="input-group-text">NAD</span>
                            </div>
                            <small class="text-muted">Import/export duties and taxes</small>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <div class="col-md-6">
                            <label for="port_charges" class="form-label">Port Charges</label>
                            <div class="input-group">
                                <input type="number" step="0.01" class="form-control" id="port_charges"
                                       name="port_charges" value="0.00" min="0">
                                <span class="input-group-text">NAD</span>
                            </div>
                            <small class="text-muted">Walvis Bay port handling fees</small>
                        </div>
                        <div class="col-md-6">
                            <label for="other_fees" class="form-label">Other Fees</label>
                            <div class="input-group">
                                <input type="number" step="0.01" class="form-control" id="other_fees"
                                       name="other_fees" value="0.00" min="0">
                                <span class="input-group-text">NAD</span>
                            </div>
                            <small class="text-muted">Documentation, insurance, etc.</small>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <div class="col-md-6">
                            <label for="currency" class="form-label">Currency</label>
                            <select class="form-select" id="currency" name="currency" required>
                                <option value="NAD" selected>NAD (Namibian Dollar)</option>
                                <option value="USD">USD (US Dollar)</option>
                                <option value="ZAR">ZAR (South African Rand)</option>
                            </select>
                        </div>
                        <div class="col-md-6">
                            <label class="form-label">Total Amount</label>
                            <div class="input-group">
                                <input type="text" class="form-control fw-bold fs-5" id="total_display"
                                       value="0.00" readonly>
                                <span class="input-group-text">NAD</span>
                            </div>
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="notes" class="form-label">Notes (Optional)</label>
                        <textarea class="form-control" id="notes" name="notes" rows="3"
                                  placeholder="Add any additional notes or payment instructions..."></textarea>
                    </div>

                    <div class="alert alert-info">
                        <strong>Payment Instructions:</strong> Once the invoice is generated, the customer will see:
                        <ul class="mb-0 mt-2">
                            <li>Invoice details and breakdown</li>
                            <li>Trade Ocean bank account details for payment</li>
                            <li>Option to upload proof of payment</li>
                        </ul>
                    </div>

                    <div class="d-flex gap-2">
                        <button type="submit" name="generate_invoice" class="btn btn-primary">
                            Generate Invoice
                        </button>
                        <a href="manage_shipments.php?id=<?= $shipmentId ?>" class="btn btn-outline-secondary">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
        <?php endif; ?>

        <div class="mt-4">
            <a href="manage_shipments.php" class="btn btn-outline-secondary">Back to Shipments</a>
        </div>
    </div>

    <!-- Footer -->
    <footer class="footer">
        <div class="container text-center">
            <p>&copy; 2025 Trade Ocean Namibia. All rights reserved.</p>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        // Auto-calculate total
        function calculateTotal() {
            const serviceFee = parseFloat(document.getElementById('service_fee').value) || 0;
            const customsDuty = parseFloat(document.getElementById('customs_duty').value) || 0;
            const portCharges = parseFloat(document.getElementById('port_charges').value) || 0;
            const otherFees = parseFloat(document.getElementById('other_fees').value) || 0;

            const total = serviceFee + customsDuty + portCharges + otherFees;
            document.getElementById('total_display').value = total.toFixed(2);
        }

        // Add event listeners
        document.getElementById('service_fee').addEventListener('input', calculateTotal);
        document.getElementById('customs_duty').addEventListener('input', calculateTotal);
        document.getElementById('port_charges').addEventListener('input', calculateTotal);
        document.getElementById('other_fees').addEventListener('input', calculateTotal);

        // Initial calculation
        calculateTotal();
    </script>
</body>
</html>
